name: Node CI

on: [push]

jobs:
  build:
    name: test job
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm run test
      env:
        CI: true
    - name: setup-opam-ocaml
      uses: fangyi-zhou/actions-ocaml@v1
      with:
        ocaml_version: 4.02.3+buckle-master
    - name: install odoc
      run: |
        opam install odoc --yes
    - name: install esy
      run: |
        npm install -g esy@0.5.6
    - name: build bsdoc
      run: |
        git clone https://github.com/reuniverse/bsdoc.git
        cd bsdoc
        esy install
        esy release
        find _release/_export/ -iname "bsdoc*" -exec tar -zxvf {} --strip-components 1 \;
    - name: Generate and deploy docs to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3-beta
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: docs
        BUILD_SCRIPT: ./bsdoc/bin/bsdoc build -v --debug PIXI
