name: Node CI

on: [push]

jobs:
  build:
    name: test job
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm run test
      env:
        CI: true
    - name: setup-opam-ocaml
      uses: fangyi-zhou/actions-ocaml@v1
      with:
        ocaml_version: 4.02.3+buckle-master
